"""add meeting fields

Revision ID: 596fffe7d9bf
Revises: b80bfcaea46e
Create Date: 2026-03-27 15:20:33.577881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596fffe7d9bf'
down_revision = 'b80bfcaea46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_start', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('date_end', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('time_start', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_end', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('assigned_user', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('teams', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('attendees_users', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attendees_contacts', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attendees_leads', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('attendees_leads')
        batch_op.drop_column('attendees_contacts')
        batch_op.drop_column('attendees_users')
        batch_op.drop_column('teams')
        batch_op.drop_column('assigned_user')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('parent_type')
        batch_op.drop_column('description')
        batch_op.drop_column('duration')
        batch_op.drop_column('time_end')
        batch_op.drop_column('time_start')
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')
        batch_op.drop_column('status')

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
