"""link contacts to accounts

Revision ID: b80bfcaea46e
Revises: 9a4d44b8f840
Create Date: 2026-03-16 12:41:35.044375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80bfcaea46e'
down_revision = '9a4d44b8f840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_postal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])
        batch_op.drop_column('account')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('first_name')
        batch_op.drop_column('department')
        batch_op.drop_column('title')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('team')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('account_id')
        batch_op.drop_column('address_country')
        batch_op.drop_column('address_postal')
        batch_op.drop_column('address_state')
        batch_op.drop_column('address_city')
        batch_op.drop_column('dob')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
